### ISSUE TITLE
TypeError: Cannot read property 'document' of null 

### ISSUE THREAD

**Issue by jrieken** [mitaki28/vscode-clang#12]
```
TypeError: Cannot read property 'document' of null 
at \mitaki28.vscode-clang-0.2.0\out\src\extension.js:71:55 
at e.invoke (\out\vs\workbench\node\pluginHostProcess.js:7:14035) 
at e.fire (\out\vs\workbench\node\pluginHostProcess.js:7:15488) 
at e._acceptActiveEditorAndVisibleEditors (\out\vs\workbench\node\pluginHostProcess.js:19:8107) 
at t.e.handle (\out\vs\workbench\node\pluginHostProcess.js:15:12835) 
at c (\out\vs\workbench\node\pluginHostProcess.js:11:16222) 
at h (\out\vs\workbench\node\pluginHostProcess.js:11:16882) 
at doNTCallback0 (node.js:420:9) 
at process._tickCallback (node.js:349:13) 
```

**Comment by mitaki28** [comment]
Sorry, I couldn't reproduce this issue, but I think it is caused because active editor is null.
So I've added null check (ebee526).
