### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by zhdaniel** [mitaki28/vscode-clang#23]
```
shell.ts:416 Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at C:\Users\zhangze1\.vscode\extensions\Shan.code-settings-sync-1.5.0\out\src\githubService.js:67:28
    at global.sendError (C:\Users\zhangze1\.vscode\extensions\Shan.code-settings-sync-1.5.0\node_modules\github4\lib\index.js:755:13)
    at C:\Users\zhangze1\.vscode\extensions\Shan.code-settings-sync-1.5.0\node_modules\github4\lib\index.js:762:29
    at callCallback (C:\Users\zhangze1\.vscode\extensions\Shan.code-settings-sync-1.5.0\node_modules\github4\lib\index.js:639:17)
    at ClientRequest.<anonymous> (C:\Users\zhangze1\.vscode\extensions\Shan.code-settings-sync-1.5.0\node_modules\github4\lib\index.js:710:17)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at TLSSocket.socketErrorListener (_http_client.js:295:9)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
```

**Comment by zhdaniel** [comment]
Sorry, I posted wrong repo.
